root = "."
tmp_dir = "tmp"

[build]
    bin = "./tmp/main"
    cmd = "go build -o ./tmp/main ./app"
    include_ext = ["go", "tpl", "tmpl", "html"]
    full_bin = ""
    log = "build-errors.log"
    stop_on_error = true

[color]
    app = ""
    build = "yellow"
    main = "magenta"
    runner = "green"
    watcher = "cyan"

[misc]
    clean_on_exit = true

[screen]
    clear_on_rebuild = true
    keep_scroll = true